name: cd-backend-appservice

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-appservice.yml'

env:
  WEBAPP_NAME: ground-truth-api-app   # Change to your Azure Web App name

jobs:
  build:
    uses: ./.github/workflows/build-backend.yml
    with:
      project-path: backend/src/GroundTruthCuration.Api/GroundTruthCuration.Api.csproj
      artifact-name: backend-publish
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-backend-appservice.yml
    with:
      webapp-name: ground-truth-api-app # (inline to avoid expression lint warnings; keep in sync with env)
      artifact-name: backend-publish
    secrets: inherit
