name: ci-backend

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/build-backend.yml'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/build-backend.yml'

jobs:
  build:
    uses: ./.github/workflows/build-backend.yml
    with:
      project-path: backend/src/GroundTruthCuration.Api/GroundTruthCuration.Api.csproj
      artifact-name: backend-publish
    secrets: inherit
